spring.application.name=shorturl
snowflake.machine-id=1
spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.dtaibvxbxisptlqmbymg
spring.datasource.password=${DB_PASSWORD}
!spring.datasource.driver-class-name=org.postgresql.Driver
!tells Hibernate to auto-create/update tables based on your entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true